// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/ratelimit.proto

package ratelimitpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AllowRequest is a single rate-limit query.
type AllowRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The key whose bucket should be charged. Typically caller-chosen
	// (e.g., user ID, API key, IP). Consistent hashing of this key is what
	// routes the request to a specific bucketd node in multi-node mode.
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// How many tokens this request wants to consume. Must be >= 1.
	Tokens int32 `protobuf:"varint,2,opt,name=tokens,proto3" json:"tokens,omitempty"`
	// Bucket configuration. Bucketd is stateless on config — the caller passes
	// the limit parameters on every Allow call. This lets a single bucketd
	// serve multiple consumers with different rate-limit shapes without any
	// server-side configuration plumbing.
	Capacity      int32   `protobuf:"varint,3,opt,name=capacity,proto3" json:"capacity,omitempty"`                        // Max tokens the bucket can hold.
	RefillRate    float64 `protobuf:"fixed64,4,opt,name=refill_rate,json=refillRate,proto3" json:"refill_rate,omitempty"` // Tokens added per second.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllowRequest) Reset() {
	*x = AllowRequest{}
	mi := &file_proto_ratelimit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllowRequest) ProtoMessage() {}

func (x *AllowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ratelimit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllowRequest.ProtoReflect.Descriptor instead.
func (*AllowRequest) Descriptor() ([]byte, []int) {
	return file_proto_ratelimit_proto_rawDescGZIP(), []int{0}
}

func (x *AllowRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *AllowRequest) GetTokens() int32 {
	if x != nil {
		return x.Tokens
	}
	return 0
}

func (x *AllowRequest) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *AllowRequest) GetRefillRate() float64 {
	if x != nil {
		return x.RefillRate
	}
	return 0
}

// AllowResponse is the verdict for a single rate-limit query.
type AllowResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True iff `tokens` were granted and deducted from the bucket.
	Allowed bool `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	// Tokens left in the bucket after this call (or before, on a deny).
	// Integer for client convenience; bucketd's internal state is fractional
	// and gets floored on the wire.
	Remaining int32 `protobuf:"varint,2,opt,name=remaining,proto3" json:"remaining,omitempty"`
	// When denied: estimated milliseconds until enough tokens refill to grant
	// the request. Zero when allowed.
	RetryAfterMs  int32 `protobuf:"varint,3,opt,name=retry_after_ms,json=retryAfterMs,proto3" json:"retry_after_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllowResponse) Reset() {
	*x = AllowResponse{}
	mi := &file_proto_ratelimit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllowResponse) ProtoMessage() {}

func (x *AllowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ratelimit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllowResponse.ProtoReflect.Descriptor instead.
func (*AllowResponse) Descriptor() ([]byte, []int) {
	return file_proto_ratelimit_proto_rawDescGZIP(), []int{1}
}

func (x *AllowResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *AllowResponse) GetRemaining() int32 {
	if x != nil {
		return x.Remaining
	}
	return 0
}

func (x *AllowResponse) GetRetryAfterMs() int32 {
	if x != nil {
		return x.RetryAfterMs
	}
	return 0
}

var File_proto_ratelimit_proto protoreflect.FileDescriptor

const file_proto_ratelimit_proto_rawDesc = "" +
	"\n" +
	"\x15proto/ratelimit.proto\x12\n" +
	"bucketd.v1\"u\n" +
	"\fAllowRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x16\n" +
	"\x06tokens\x18\x02 \x01(\x05R\x06tokens\x12\x1a\n" +
	"\bcapacity\x18\x03 \x01(\x05R\bcapacity\x12\x1f\n" +
	"\vrefill_rate\x18\x04 \x01(\x01R\n" +
	"refillRate\"m\n" +
	"\rAllowResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12\x1c\n" +
	"\tremaining\x18\x02 \x01(\x05R\tremaining\x12$\n" +
	"\x0eretry_after_ms\x18\x03 \x01(\x05R\fretryAfterMs2K\n" +
	"\vRateLimiter\x12<\n" +
	"\x05Allow\x12\x18.bucketd.v1.AllowRequest\x1a\x19.bucketd.v1.AllowResponseB1Z/github.com/kevinreber/bucketd/proto;ratelimitpbb\x06proto3"

var (
	file_proto_ratelimit_proto_rawDescOnce sync.Once
	file_proto_ratelimit_proto_rawDescData []byte
)

func file_proto_ratelimit_proto_rawDescGZIP() []byte {
	file_proto_ratelimit_proto_rawDescOnce.Do(func() {
		file_proto_ratelimit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ratelimit_proto_rawDesc), len(file_proto_ratelimit_proto_rawDesc)))
	})
	return file_proto_ratelimit_proto_rawDescData
}

var file_proto_ratelimit_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_ratelimit_proto_goTypes = []any{
	(*AllowRequest)(nil),  // 0: bucketd.v1.AllowRequest
	(*AllowResponse)(nil), // 1: bucketd.v1.AllowResponse
}
var file_proto_ratelimit_proto_depIdxs = []int32{
	0, // 0: bucketd.v1.RateLimiter.Allow:input_type -> bucketd.v1.AllowRequest
	1, // 1: bucketd.v1.RateLimiter.Allow:output_type -> bucketd.v1.AllowResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_ratelimit_proto_init() }
func file_proto_ratelimit_proto_init() {
	if File_proto_ratelimit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ratelimit_proto_rawDesc), len(file_proto_ratelimit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ratelimit_proto_goTypes,
		DependencyIndexes: file_proto_ratelimit_proto_depIdxs,
		MessageInfos:      file_proto_ratelimit_proto_msgTypes,
	}.Build()
	File_proto_ratelimit_proto = out.File
	file_proto_ratelimit_proto_goTypes = nil
	file_proto_ratelimit_proto_depIdxs = nil
}
